import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export type Language = 'en' | 'es' | 'fr' | 'de' | 'zh' | 'ja' | 'ar' | 'pt';

interface LanguageInfo {
  code: Language;
  name: string;
  nativeName: string;
  flag: string;
}

export const languages: LanguageInfo[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇺🇸' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪' },
  { code: 'zh', name: 'Chinese', nativeName: '中文', flag: '🇨🇳' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', flag: '🇧🇷' },
];

// Static translations for common UI elements
const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.suites': 'Suites',
    'nav.deals': 'Deals',
    'nav.dashboard': 'Dashboard',
    'nav.signin': 'Sign In',
    'nav.profile': 'Profile',
    'hero.tagline': 'Premium Luxury Hotel',
    'hero.title': 'Lotus Heaven',
    'hero.subtitle': 'Where luxury meets tranquility in perfect harmony',
    'hero.explore': 'Explore Our Suites',
    'hero.tour': 'Virtual Tour',
    'rooms.title': 'Luxury Suites',
    'rooms.subtitle': 'Discover our curated selection of world-class accommodations',
    'rooms.showing': 'Showing',
    'rooms.suites': 'luxury suites',
    'booking.details': 'Booking Details',
    'booking.payment': 'Payment Information',
    'booking.confirmed': 'Booking Confirmed!',
    'booking.continue': 'Continue to Payment',
    'booking.confirm': 'Confirm & Pay',
    'loyalty.member': 'Member',
    'loyalty.points': 'Points',
    'loyalty.benefits': 'Your Benefits',
    'loyalty.progress': 'Progress to',
    'loyalty.lifetime': 'Lifetime Points',
    'loyalty.redeem': 'Redeem Points',
    'search.placeholder': 'Search rooms...',
    'search.filters': 'Filters',
    'common.viewDetails': 'View Details',
    'common.perNight': 'per night',
    'common.guests': 'guests',
    'common.book': 'Book Now',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.loading': 'Loading...',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.suites': 'Suites',
    'nav.deals': 'Ofertas',
    'nav.dashboard': 'Panel',
    'nav.signin': 'Iniciar Sesión',
    'nav.profile': 'Perfil',
    'hero.tagline': 'Hotel de Lujo Premium',
    'hero.title': 'Lotus Heaven',
    'hero.subtitle': 'Donde el lujo se encuentra con la tranquilidad en perfecta armonía',
    'hero.explore': 'Explorar Nuestras Suites',
    'hero.tour': 'Tour Virtual',
    'rooms.title': 'Suites de Lujo',
    'rooms.subtitle': 'Descubre nuestra selección curada de alojamientos de clase mundial',
    'rooms.showing': 'Mostrando',
    'rooms.suites': 'suites de lujo',
    'booking.details': 'Detalles de Reserva',
    'booking.payment': 'Información de Pago',
    'booking.confirmed': '¡Reserva Confirmada!',
    'booking.continue': 'Continuar al Pago',
    'booking.confirm': 'Confirmar y Pagar',
    'loyalty.member': 'Miembro',
    'loyalty.points': 'Puntos',
    'loyalty.benefits': 'Tus Beneficios',
    'loyalty.progress': 'Progreso hacia',
    'loyalty.lifetime': 'Puntos de por Vida',
    'loyalty.redeem': 'Canjear Puntos',
    'search.placeholder': 'Buscar habitaciones...',
    'search.filters': 'Filtros',
    'common.viewDetails': 'Ver Detalles',
    'common.perNight': 'por noche',
    'common.guests': 'huéspedes',
    'common.book': 'Reservar',
    'common.cancel': 'Cancelar',
    'common.save': 'Guardar',
    'common.loading': 'Cargando...',
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.suites': 'Suites',
    'nav.deals': 'Offres',
    'nav.dashboard': 'Tableau de bord',
    'nav.signin': 'Connexion',
    'nav.profile': 'Profil',
    'hero.tagline': 'Hôtel de Luxe Premium',
    'hero.title': 'Lotus Heaven',
    'hero.subtitle': 'Où le luxe rencontre la tranquillité en parfaite harmonie',
    'hero.explore': 'Explorer Nos Suites',
    'hero.tour': 'Visite Virtuelle',
    'rooms.title': 'Suites de Luxe',
    'rooms.subtitle': 'Découvrez notre sélection d\'hébergements de classe mondiale',
    'rooms.showing': 'Affichage',
    'rooms.suites': 'suites de luxe',
    'booking.details': 'Détails de Réservation',
    'booking.payment': 'Informations de Paiement',
    'booking.confirmed': 'Réservation Confirmée!',
    'booking.continue': 'Continuer au Paiement',
    'booking.confirm': 'Confirmer et Payer',
    'loyalty.member': 'Membre',
    'loyalty.points': 'Points',
    'loyalty.benefits': 'Vos Avantages',
    'loyalty.progress': 'Progression vers',
    'loyalty.lifetime': 'Points à Vie',
    'loyalty.redeem': 'Échanger Points',
    'search.placeholder': 'Rechercher des chambres...',
    'search.filters': 'Filtres',
    'common.viewDetails': 'Voir Détails',
    'common.perNight': 'par nuit',
    'common.guests': 'invités',
    'common.book': 'Réserver',
    'common.cancel': 'Annuler',
    'common.save': 'Enregistrer',
    'common.loading': 'Chargement...',
  },
  de: {
    'nav.home': 'Startseite',
    'nav.suites': 'Suiten',
    'nav.deals': 'Angebote',
    'nav.dashboard': 'Dashboard',
    'nav.signin': 'Anmelden',
    'nav.profile': 'Profil',
    'hero.tagline': 'Premium Luxushotel',
    'hero.title': 'Lotus Heaven',
    'hero.subtitle': 'Wo Luxus und Ruhe in perfekter Harmonie zusammentreffen',
    'hero.explore': 'Unsere Suiten Erkunden',
    'hero.tour': 'Virtuelle Tour',
    'rooms.title': 'Luxus-Suiten',
    'rooms.subtitle': 'Entdecken Sie unsere kuratierte Auswahl erstklassiger Unterkünfte',
    'rooms.showing': 'Zeige',
    'rooms.suites': 'Luxus-Suiten',
    'booking.details': 'Buchungsdetails',
    'booking.payment': 'Zahlungsinformationen',
    'booking.confirmed': 'Buchung Bestätigt!',
    'booking.continue': 'Weiter zur Zahlung',
    'booking.confirm': 'Bestätigen & Bezahlen',
    'loyalty.member': 'Mitglied',
    'loyalty.points': 'Punkte',
    'loyalty.benefits': 'Ihre Vorteile',
    'loyalty.progress': 'Fortschritt zu',
    'loyalty.lifetime': 'Lebenslange Punkte',
    'loyalty.redeem': 'Punkte Einlösen',
    'search.placeholder': 'Zimmer suchen...',
    'search.filters': 'Filter',
    'common.viewDetails': 'Details Anzeigen',
    'common.perNight': 'pro Nacht',
    'common.guests': 'Gäste',
    'common.book': 'Buchen',
    'common.cancel': 'Abbrechen',
    'common.save': 'Speichern',
    'common.loading': 'Laden...',
  },
  zh: {
    'nav.home': '首页',
    'nav.suites': '套房',
    'nav.deals': '优惠',
    'nav.dashboard': '仪表板',
    'nav.signin': '登录',
    'nav.profile': '个人资料',
    'hero.tagline': '高级豪华酒店',
    'hero.title': 'Lotus Heaven',
    'hero.subtitle': '奢华与宁静完美融合',
    'hero.explore': '探索我们的套房',
    'hero.tour': '虚拟导览',
    'rooms.title': '豪华套房',
    'rooms.subtitle': '发现我们精选的世界级住宿',
    'rooms.showing': '显示',
    'rooms.suites': '豪华套房',
    'booking.details': '预订详情',
    'booking.payment': '付款信息',
    'booking.confirmed': '预订确认！',
    'booking.continue': '继续付款',
    'booking.confirm': '确认并付款',
    'loyalty.member': '会员',
    'loyalty.points': '积分',
    'loyalty.benefits': '您的福利',
    'loyalty.progress': '升级进度',
    'loyalty.lifetime': '终身积分',
    'loyalty.redeem': '兑换积分',
    'search.placeholder': '搜索房间...',
    'search.filters': '筛选',
    'common.viewDetails': '查看详情',
    'common.perNight': '每晚',
    'common.guests': '客人',
    'common.book': '立即预订',
    'common.cancel': '取消',
    'common.save': '保存',
    'common.loading': '加载中...',
  },
  ja: {
    'nav.home': 'ホーム',
    'nav.suites': 'スイート',
    'nav.deals': '特典',
    'nav.dashboard': 'ダッシュボード',
    'nav.signin': 'サインイン',
    'nav.profile': 'プロフィール',
    'hero.tagline': 'プレミアムラグジュアリーホテル',
    'hero.title': 'Lotus Heaven',
    'hero.subtitle': '贅沢と静けさが完璧に調和する場所',
    'hero.explore': 'スイートを探索',
    'hero.tour': 'バーチャルツアー',
    'rooms.title': 'ラグジュアリースイート',
    'rooms.subtitle': '厳選されたワールドクラスの宿泊施設をご覧ください',
    'rooms.showing': '表示中',
    'rooms.suites': 'ラグジュアリースイート',
    'booking.details': '予約詳細',
    'booking.payment': '支払い情報',
    'booking.confirmed': '予約確定！',
    'booking.continue': '支払いに進む',
    'booking.confirm': '確認して支払う',
    'loyalty.member': 'メンバー',
    'loyalty.points': 'ポイント',
    'loyalty.benefits': '特典',
    'loyalty.progress': '進捗',
    'loyalty.lifetime': '生涯ポイント',
    'loyalty.redeem': 'ポイント交換',
    'search.placeholder': '部屋を検索...',
    'search.filters': 'フィルター',
    'common.viewDetails': '詳細を見る',
    'common.perNight': '/泊',
    'common.guests': '名',
    'common.book': '予約する',
    'common.cancel': 'キャンセル',
    'common.save': '保存',
    'common.loading': '読み込み中...',
  },
  ar: {
    'nav.home': 'الرئيسية',
    'nav.suites': 'الأجنحة',
    'nav.deals': 'العروض',
    'nav.dashboard': 'لوحة التحكم',
    'nav.signin': 'تسجيل الدخول',
    'nav.profile': 'الملف الشخصي',
    'hero.tagline': 'فندق فاخر متميز',
    'hero.title': 'Lotus Heaven',
    'hero.subtitle': 'حيث تلتقي الفخامة بالهدوء في تناغم تام',
    'hero.explore': 'استكشف أجنحتنا',
    'hero.tour': 'جولة افتراضية',
    'rooms.title': 'أجنحة فاخرة',
    'rooms.subtitle': 'اكتشف مجموعتنا المنتقاة من أماكن الإقامة العالمية',
    'rooms.showing': 'عرض',
    'rooms.suites': 'أجنحة فاخرة',
    'booking.details': 'تفاصيل الحجز',
    'booking.payment': 'معلومات الدفع',
    'booking.confirmed': 'تم تأكيد الحجز!',
    'booking.continue': 'متابعة للدفع',
    'booking.confirm': 'تأكيد ودفع',
    'loyalty.member': 'عضو',
    'loyalty.points': 'نقاط',
    'loyalty.benefits': 'مزاياك',
    'loyalty.progress': 'التقدم نحو',
    'loyalty.lifetime': 'نقاط مدى الحياة',
    'loyalty.redeem': 'استبدال النقاط',
    'search.placeholder': 'البحث عن غرف...',
    'search.filters': 'الفلاتر',
    'common.viewDetails': 'عرض التفاصيل',
    'common.perNight': 'لليلة',
    'common.guests': 'ضيوف',
    'common.book': 'احجز الآن',
    'common.cancel': 'إلغاء',
    'common.save': 'حفظ',
    'common.loading': 'جار التحميل...',
  },
  pt: {
    'nav.home': 'Início',
    'nav.suites': 'Suítes',
    'nav.deals': 'Ofertas',
    'nav.dashboard': 'Painel',
    'nav.signin': 'Entrar',
    'nav.profile': 'Perfil',
    'hero.tagline': 'Hotel de Luxo Premium',
    'hero.title': 'Lotus Heaven',
    'hero.subtitle': 'Onde o luxo encontra a tranquilidade em perfeita harmonia',
    'hero.explore': 'Explorar Nossas Suítes',
    'hero.tour': 'Tour Virtual',
    'rooms.title': 'Suítes de Luxo',
    'rooms.subtitle': 'Descubra nossa seleção curada de acomodações de classe mundial',
    'rooms.showing': 'Mostrando',
    'rooms.suites': 'suítes de luxo',
    'booking.details': 'Detalhes da Reserva',
    'booking.payment': 'Informações de Pagamento',
    'booking.confirmed': 'Reserva Confirmada!',
    'booking.continue': 'Continuar para Pagamento',
    'booking.confirm': 'Confirmar e Pagar',
    'loyalty.member': 'Membro',
    'loyalty.points': 'Pontos',
    'loyalty.benefits': 'Seus Benefícios',
    'loyalty.progress': 'Progresso para',
    'loyalty.lifetime': 'Pontos Vitalícios',
    'loyalty.redeem': 'Resgatar Pontos',
    'search.placeholder': 'Pesquisar quartos...',
    'search.filters': 'Filtros',
    'common.viewDetails': 'Ver Detalhes',
    'common.perNight': 'por noite',
    'common.guests': 'hóspedes',
    'common.book': 'Reservar',
    'common.cancel': 'Cancelar',
    'common.save': 'Salvar',
    'common.loading': 'Carregando...',
  },
};

interface LanguageState {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

export const useLanguageStore = create<LanguageState>()(
  persist(
    (set, get) => ({
      language: 'en',
      setLanguage: (lang) => set({ language: lang }),
      t: (key) => {
        const lang = get().language;
        return translations[lang]?.[key] || translations['en']?.[key] || key;
      },
    }),
    {
      name: 'language-storage',
    }
  )
);
